# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "cloudfoundry-vagrant"
  config.vm.box_url = "https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../chef/cookbooks"
    chef.roles_path = "../chef/roles"
    chef.data_bags_path = "../chef/data_bags"

    chef.add_recipe "cloudfoundry-dea"

    chef.json = {
    }
  end
end